### ISSUE TITLE
Ask for help of On-Demand Service Predition

### ISSUE THREAD

**Issue by lmx88460725** [LibCity/Bigscity-LibCity#173]
Thanks for your great job!

I am interested in the CCRNN model for the on-demand service prediction task. However, I don't know which dataset can be used in this model. Could you please help tell me the answer?
By the way, a list to introduce which dataset is suitable for the corresponding task may be greatly helpful for us. 

Thanks again and look forward to your reply~

**Comment by aptx1231** [comment]
Hello, the CCRNN model can be used for several sensor-based traffic data sets such as METR_LA, PEMS_BAY, PEMSD3/4/7/8, and it is also suitable for traffic datasets calculated from trajectories such as NYCTAXI_DYNA.

In fact, the CCRNN model is also suitable for grid datasets like NYCTAXI_GRID, TAXIBJ, T_DRIVE, but you need to make simple modifications. That is, modify the file `libcity/data/dataset/traffic_state_grid_dataset.py` to make the  `CCRNNDataset` inherit `TrafficStateGridDataset` instead of the current `TrafficStatePointDataset`.

You mentioned a list to introduce which dataset is suitable for the corresponding task. We think this is a good suggestion. We will add it to our document **within 1~2 days**, and we will remind you here when we are done.

Thank you for your suggestion!

**Comment by aptx1231** [comment]
Hi, we have released the correspondence between datasets and tasks at [here](https://bigscity-libcity-docs.readthedocs.io/en/latest/user_guide/data/dataset_for_task.html). If you have any questions, please feel free to contact us!

**Comment by lmx88460725** [comment]
Thanks for your kind reply!
