### ISSUE TITLE
[DCRNN] Minor error: 'output_dim' is supposed to be saved in config

### ISSUE THREAD

**Issue by Jum596116882** [LibCity/Bigscity-LibCity#275]
https://github.com/LibCity/Bigscity-LibCity/blob/939ef5dc46f3b2e0d665a11a9bc03ccd4423ca0c/libcity/model/traffic_speed_prediction/DCRNN.py#L339
I think the code following should be added because config['output_dim'] is visited in DecoderModel but there seems no definition of that.
`config['output_dim'] = self.output_dim`
It seems to be a minor error and thanks for your hard-working. I learned a lot from it!

**Comment by aptx1231** [comment]
Yes, this was a bug in our previous design, in the current [latest code](https://github.com/LibCity/Bigscity-LibCity/blob/master/libcity/model/traffic_speed_prediction/DCRNN.py#L296) for the parameter `output_dim` we have made it uniformly taken from `config` instead of going through `data_feature`. Thank you for using it, and please feel free to contact us if you have any questions!
